### ISSUE TITLE
Alternative license

### ISSUE THREAD

**Issue by matheus23** [adaszko/diag#1]
Hi @adaszko :wave: 
Would you be willing to re-license this under a more permissive license such as Apache 2.0 or MIT?
I'd love to use this library and integrate it with some proptest tests I'm writing in a project that's Apache 2.0/MIT dual-licensed.

**Comment by adaszko** [comment]
Oh, cool, is that for https://github.com/wnfs-wg/rs-wnfs ?  I actually have a proptest-based DAGs generation code in an unpushed repo.  I’d love to hear more about what you need to use this code for

**Comment by matheus23** [comment]
It's for another project, it's at https://github.com/fission-codes/rs-car-mirror right now, but private (will be public soon!).
But it's related. rs-wnfs encodes as so-called ["IPLD"](https://ipld.io/), which means it can be stored in IPFS.
Car mirror is a [protocol](https://github.com/fission-codes/spec/blob/main/car-pool/car-mirror/SPEC.md) for sending around any kind of IPLD data between nodes, making sure to deduplicate data and minimize round-trips while doing so and not sending stuff twice.

It'd be nice to generate arbitrary IPLD DAGs and test the car mirror implementation on such data.

**Comment by adaszko** [comment]
Thanks for sharing 👍 

I just published https://crates.io/crates/roaring-graphs as a better successor to dograph.  dograph repo will be archived soon.

Take a look at [`arb_dag()`](https://github.com/adaszko/roaring-graphs/blob/9c9771b6dfba80f8de46c67340f48f47d24ab059/src/dag.rs#L407) fn in particular.  Contributions are welcome of course.

**Comment by matheus23** [comment]
Taking a look :eyes: 
Thank you so much! :)
